import RecoverStaminaByUserId from "../stampSheet/RecoverStaminaByUserId";
import RaiseMaxValueByUserId from "../stampSheet/RaiseMaxValueByUserId";
import SetMaxValueByUserId from "../stampSheet/SetMaxValueByUserId";
import SetRecoverIntervalByUserId from "../stampSheet/SetRecoverIntervalByUserId";
import SetRecoverValueByUserId from "../stampSheet/SetRecoverValueByUserId";
import DecreaseMaxValueByUserId from "../stampSheet/DecreaseMaxValueByUserId";
import ConsumeStaminaByUserId from "../stampSheet/ConsumeStaminaByUserId";
import VerifyStaminaValueByUserId from "../stampSheet/VerifyStaminaValueByUserId";
import { StaminaVerifyType } from "../stampSheet/enums/StaminaVerifyType";
import VerifyStaminaMaxValueByUserId from "../stampSheet/VerifyStaminaMaxValueByUserId";
import VerifyStaminaRecoverIntervalMinutesByUserId from "../stampSheet/VerifyStaminaRecoverIntervalMinutesByUserId";
import VerifyStaminaRecoverValueByUserId from "../stampSheet/VerifyStaminaRecoverValueByUserId";
import VerifyStaminaOverflowValueByUserId from "../stampSheet/VerifyStaminaOverflowValueByUserId";
export default class StaminaModelRef {
    private readonly namespaceName;
    private readonly staminaName;
    constructor(namespaceName: string, staminaName: string);
    recoverStamina(recoverValue: number, userId?: string): RecoverStaminaByUserId;
    raiseMaxValue(raiseValue: number, userId?: string): RaiseMaxValueByUserId;
    setMaxValue(maxValue: number, userId?: string): SetMaxValueByUserId;
    setRecoverInterval(recoverIntervalMinutes: number, userId?: string): SetRecoverIntervalByUserId;
    setRecoverValue(recoverValue: number, userId?: string): SetRecoverValueByUserId;
    decreaseMaxValue(decreaseValue: number, userId?: string): DecreaseMaxValueByUserId;
    consumeStamina(consumeValue: number, userId?: string): ConsumeStaminaByUserId;
    verifyStaminaValue(verifyType: StaminaVerifyType, value: number, multiplyValueSpecifyingQuantity?: boolean | null, userId?: string): VerifyStaminaValueByUserId;
    verifyStaminaMaxValue(verifyType: StaminaVerifyType, value: number, multiplyValueSpecifyingQuantity?: boolean | null, userId?: string): VerifyStaminaMaxValueByUserId;
    verifyStaminaRecoverIntervalMinutes(verifyType: StaminaVerifyType, value: number, multiplyValueSpecifyingQuantity?: boolean | null, userId?: string): VerifyStaminaRecoverIntervalMinutesByUserId;
    verifyStaminaRecoverValue(verifyType: StaminaVerifyType, value: number, multiplyValueSpecifyingQuantity?: boolean | null, userId?: string): VerifyStaminaRecoverValueByUserId;
    verifyStaminaOverflowValue(verifyType: StaminaVerifyType, value: number, multiplyValueSpecifyingQuantity?: boolean | null, userId?: string): VerifyStaminaOverflowValueByUserId;
    grn(): string;
}
