export declare const BuffTargetModelTargetModelName: {
    readonly GS2_EXCHANGE_INCREMENTAL_RATE_MODEL: "Gs2Exchange:IncrementalRateModel";
    readonly GS2_EXCHANGE_RATE_MODEL: "Gs2Exchange:RateModel";
    readonly GS2_EXPERIENCE_EXPERIENCE_MODEL: "Gs2Experience:ExperienceModel";
    readonly GS2_EXPERIENCE_STATUS: "Gs2Experience:Status";
    readonly GS2_FORMATION_MOLD: "Gs2Formation:Mold";
    readonly GS2_IDLE_CATEGORY_MODEL: "Gs2Idle:CategoryModel";
    readonly GS2_IDLE_STATUS: "Gs2Idle:Status";
    readonly GS2_INVENTORY_BIG_INVENTORY_MODEL: "Gs2Inventory:BigInventoryModel";
    readonly GS2_INVENTORY_BIG_ITEM_MODEL: "Gs2Inventory:BigItemModel";
    readonly GS2_INVENTORY_INVENTORY: "Gs2Inventory:Inventory";
    readonly GS2_INVENTORY_INVENTORY_MODEL: "Gs2Inventory:InventoryModel";
    readonly GS2_INVENTORY_ITEM_MODEL: "Gs2Inventory:ItemModel";
    readonly GS2_INVENTORY_SIMPLE_INVENTORY_MODEL: "Gs2Inventory:SimpleInventoryModel";
    readonly GS2_INVENTORY_SIMPLE_ITEM_MODEL: "Gs2Inventory:SimpleItemModel";
    readonly GS2_LIMIT_COUNTER: "Gs2Limit:Counter";
    readonly GS2_LIMIT_LIMIT_MODEL: "Gs2Limit:LimitModel";
    readonly GS2_LOGIN_REWARD_BONUS_MODEL: "Gs2LoginReward:BonusModel";
    readonly GS2_MISSION_MISSION_TASK_MODEL: "Gs2Mission:MissionTaskModel";
    readonly GS2_MONEY2_WALLET: "Gs2Money2:Wallet";
    readonly GS2_MONEY_WALLET: "Gs2Money:Wallet";
    readonly GS2_QUEST_QUEST_MODEL: "Gs2Quest:QuestModel";
    readonly GS2_SHOWCASE_DISPLAY_ITEM: "Gs2Showcase:DisplayItem";
    readonly GS2_SHOWCASE_RANDOM_DISPLAY_ITEM_MODEL: "Gs2Showcase:RandomDisplayItemModel";
    readonly GS2_SKILL_TREE_NODE_MODEL: "Gs2SkillTree:NodeModel";
    readonly GS2_STAMINA_STAMINA: "Gs2Stamina:Stamina";
    readonly GS2_STAMINA_STAMINA_MODEL: "Gs2Stamina:StaminaModel";
};
export type BuffTargetModelTargetModelName = typeof BuffTargetModelTargetModelName[keyof typeof BuffTargetModelTargetModelName];
